// Generated by CoffeeScript 1.10.0
(function() {
  var Promise, fs;

  Promise = require('bluebird');

  fs = Promise.promisifyAll(require('fs'));

  exports.scan = function() {
    fs.readdirAsync('./test_files').then(function(files) {
      files.forEach(function(file) {
        console.log(file);
      });
    });
  };

}).call(this);
