// Generated by CoffeeScript 1.10.0
(function() {
  var Promise, fs;

  Promise = require('bluebird');

  fs = Promise.promisifyAll(require('fs'));

  exports.save = function(file, msg) {
    return fs.writeFileAsync(file, msg).then(function() {
      console.log('It\'s saved!');
    }).error(function(error) {
      console.log(error);
    });
  };

}).call(this);
