// Generated by CoffeeScript 1.10.0
(function() {
  var Promise, app, express, fs;

  express = require('express');

  app = express();

  Promise = require('bluebird');

  fs = Promise.promisifyAll(require('fs'));

  fs.writeFileAsync('./test_files/message1.txt', 'Hello Node!').then(function() {
    console.log('It\'s saved!');
  }).error(function(error) {
    console.log(error);
  });

}).call(this);
