// Generated by CoffeeScript 1.10.0
(function() {
  var Promise, app, express, file, fileManager;

  express = require('express');

  app = express();

  Promise = require('bluebird');

  file = require('./file');

  fileManager = require('./file_manager');

  setInterval(function() {
    fileManager.scan();
  }, 3000);

}).call(this);
